# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 192819d4eb84ca0087b370a6f9cafed81d3f505255ea36ccc04c5a5db1c58a126ea120c88dd26f20fde32d6da7e7f0a685a7d292af0007be736b1e25eaaf8c32

test:
  secret_key_base: 0f483a6c44a42304d3270e01506950863ce3305d40b3e6942cbaaeb72434b4918f88fc31d6173693e5de6d57541f5902a3b303cb9a335485849c6461fa8a6202

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
